/* =========================================================================
   WISY SAFETY — Registre des SOURCES et des AFFIRMATIONS vérifiées (pages « fiche » du 2026-10-01)
   -------------------------------------------------------------------------
   Une affirmation publiée = un identifiant SRC-… posé dans le HTML (attribut data-src="SRC-…") et décrit ICI :
   texte publié, document source, passage justificatif, deuxième source si l'information est critique, statut.

     • DOCUMENTS : chaque document réellement OUVERT et LU pendant la vérification (URL trouvée par recherche ou par
       lien, jamais construite de mémoire), avec son type : Official · Professional · Secondary · Primary (Wisy Safety).
     • CLAIMS    : les affirmations, avec leur statut (Verified · Corrected · Needs confirmation · Removed).

   Utilisé par : scripts/check-sources.js (échoue si une affirmation affichée n'a pas de source vérifiée ou si une page
   contient « [À CONFIRMER] »), scripts/check-external-links.js (disponibilité des liens), scripts/build-sources-doc.js
   (génère docs/content-sources.md) et scripts/build-seo.js (propriété `citation` des articles).
   Jamais chargé par les pages (aucun poids sur le chemin critique). Module « dual-mode » (navigateur / Node).
   ========================================================================= */
(function (root, factory) {
  "use strict";
  var api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  root.WisySources = api;
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";

  var CHECKED = "2026-10-01";

  /* ------------------------------------------------------------------ documents consultés */
  var DOCUMENTS = [
    { id: "DOC-EURLEX-2020-1149", type: "Official", org: "Union européenne — EUR-Lex",
      title: "Règlement (UE) 2020/1149 de la Commission du 3 août 2020 modifiant l'annexe XVII du règlement (CE) n° 1907/2006 (REACH) en ce qui concerne les diisocyanates — JO L 252 du 4.8.2020, p. 24",
      url: "https://eur-lex.europa.eu/legal-content/FR/TXT/HTML/?uri=CELEX:32020R1149",
      urls: { fr: "https://eur-lex.europa.eu/legal-content/FR/TXT/HTML/?uri=CELEX:32020R1149", nl: "https://eur-lex.europa.eu/legal-content/NL/TXT/HTML/?uri=CELEX:32020R1149",
        en: "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32020R1149", de: "https://eur-lex.europa.eu/legal-content/DE/TXT/HTML/?uri=CELEX:32020R1149",
        bg: "https://eur-lex.europa.eu/legal-content/BG/TXT/HTML/?uri=CELEX:32020R1149", ro: "https://eur-lex.europa.eu/legal-content/RO/TXT/HTML/?uri=CELEX:32020R1149",
        it: "https://eur-lex.europa.eu/legal-content/IT/TXT/HTML/?uri=CELEX:32020R1149", sl: "https://eur-lex.europa.eu/legal-content/SL/TXT/HTML/?uri=CELEX:32020R1149" },
      note: "Texte français lu intégralement (considérants, articles, annexe). Versions linguistiques : liens relevés sur la page ELI https://eur-lex.europa.eu/eli/reg/2020/1149/oj (texte officiel du même acte, non relu langue par langue). Version d'origine de l'acte modificatif ; aucune modification ultérieure de l'entrée 74 n'a été relevée pendant la vérification (version consolidée de l'annexe XVII non consultée)." },
    { id: "DOC-ECHA-DIISO", type: "Official", org: "Agence européenne des produits chimiques (ECHA)",
      title: "Substance Information — Diisocyanates (groupe de 14 substances)", url: "https://echa.europa.eu/substance-information/-/substanceinfo/100.251.385" },
    { id: "DOC-SPF-VLE-2026", type: "Official", org: "SPF Emploi, Travail et Concertation sociale",
      title: "Nouvelles valeurs limites d'exposition professionnelle pour le plomb, ses composés et les diisocyanates (actualité du 3 juin 2026)",
      url: "https://emploi.belgique.be/fr/actualites/nouvelles-valeurs-limites-dexposition-professionnelle-pour-le-plomb-ses-composes-et-les",
      note: "Renvoie à l'arrêté royal du 25 mai 2026 (Moniteur belge du 3 juin 2026) et à la directive (UE) 2024/869 — textes eux-mêmes non relus." },
    { id: "DOC-SPF-AGENTS-CHIM", type: "Official", org: "SPF Emploi, Travail et Concertation sociale",
      title: "Agents chimiques — Code du bien-être au travail, livre VI, titre 1er", url: "https://emploi.belgique.be/fr/themes/bien-etre-au-travail/agents-chimiques-cancerigenes-mutagenes-et-reprotoxiques-et-agents-2" },
    { id: "DOC-ISOPA", type: "Professional", org: "ISOPA (European Diisocyanate & Polyol Producers Association)",
      title: "ISOPA — page d'accueil (« ISOPA represents the manufacturers of aromatic diisocyanates and polyols, the main raw materials for polyurethanes in Europe »)", url: "https://www.isopa.org/" },
    { id: "DOC-ALIPA", type: "Professional", org: "ALIPA (European Aliphatic Isocyanates Producers Association)",
      title: "ALIPA — Product stewardship", url: "https://www.alipa.org/product-stewardship/" },
    { id: "DOC-EURLEX-1999-77", type: "Official", org: "Union européenne — EUR-Lex",
      title: "Directive 1999/77/CE de la Commission du 26 juillet 1999 (amiante)", url: "https://eur-lex.europa.eu/legal-content/FR/ALL/?uri=CELEX:31999L0077",
      note: "Considérants et articles lus ; l'annexe n'est publiée sur EUR-Lex que sous forme d'image (non relue) : le site n'en cite rien." },
    { id: "DOC-EURLEX-2017-2398", type: "Official", org: "Union européenne — EUR-Lex",
      title: "Directive (UE) 2017/2398 du Parlement européen et du Conseil du 12 décembre 2017 (agents cancérigènes ou mutagènes) — JO L 345 du 27.12.2017", url: "https://eur-lex.europa.eu/legal-content/FR/TXT/HTML/?uri=CELEX:32017L2398" },
    { id: "DOC-EURLEX-2019-983", type: "Official", org: "Union européenne — EUR-Lex",
      title: "Directive (UE) 2019/983 du Parlement européen et du Conseil du 5 juin 2019 (agents cancérigènes ou mutagènes) — JO L 164 du 20.6.2019", url: "https://eur-lex.europa.eu/legal-content/FR/TXT/HTML/?uri=CELEX:32019L0983" },
    { id: "DOC-ECHA-CRO3", type: "Official", org: "Agence européenne des produits chimiques (ECHA)",
      title: "Authorisation List — Chromium trioxide (entrée 16)", url: "https://echa.europa.eu/authorisation-list/-/dislist/details/0b0236e1807e0228" },
    { id: "DOC-BESACC-VOL", type: "Official", org: "BeSaCC-VCA (Contractor Safety Management asbl)",
      title: "Sécurité pour les gestionnaires opérationnels (VOL-VCA)", url: "https://www.besacc-vca.be/fr/veiligheid-voor-operationeel-leidinggevenden-vol-vca/",
      urls: { fr: "https://www.besacc-vca.be/fr/veiligheid-voor-operationeel-leidinggevenden-vol-vca/", nl: "https://www.besacc-vca.be/veiligheid-voor-operationeel-leidinggevenden-vol-vca/", en: "https://www.besacc-vca.be/en/veiligheid-voor-operationeel-leidinggevenden-vol-vca/" },
      note: "Versions NL et EN : liens hreflang de la page." },
    { id: "DOC-BESACC-ETT-VOL", type: "Official", org: "BeSaCC-VCA",
      title: "Rapportage Eind- en Toetstermen VCA VOL, version du 01-04-2015 (PDF, néerlandais)", url: "https://www.besacc-vca.be/wp-content/uploads/2023/06/Eind-en-toetstermen-VCA-VOL-versie-01-04-2015_1.pdf",
      note: "Lien publié sur la page VOL-VCA de BeSaCC-VCA. Aux Pays-Bas, SSVV publie une version ETT v3.0 (2026) — non reprise par BeSaCC à la date de vérification." },
    { id: "DOC-CSM-REGLEMENT", type: "Official", org: "Contractor Safety Management (BeSaCC-VCA)",
      title: "Règlement général des examens VCA — version 2018-03 (PDF)", url: "https://www.besacc-vca.be/wp-content/uploads/2023/06/Reglement-General-Examens-VCA-2018-03.pdf",
      note: "Lien publié sur la page « Règlement d'examen VCA » de BeSaCC-VCA. Le site citait jusqu'ici une copie sous /2023/09/ : contrôlée par scripts/check-external-links.js." },
    { id: "DOC-VI-REGLEMENT-2024", type: "Professional", org: "Veiligheidsinstituut (AP Hogeschool) — centre d'examen reconnu par BeSaCC-VCA",
      title: "VI : règlement des examens VCA sur ordinateur, version du 06/11/2024 (PDF, français)", url: "https://www.ap.be/sites/default/files/users/user8505/FR-VI%20reglement%20VCA-CBT%20examens%20NL%202024.pdf" },
    { id: "DOC-CONSTRUCTIV-VCA", type: "Professional", org: "Constructiv — fonds sectoriel de la construction, centre d'examen reconnu par BeSaCC-VCA",
      title: "Offre VCA Constructiv (types de questions, score de réussite)", url: "https://constructiv.be/fr/certificats-attestations/offre-vca-constructiv/" },
    { id: "DOC-BESACC-CENTRES", type: "Official", org: "BeSaCC-VCA",
      title: "Centres d'examen reconnus (B-VCA, VOL-VCA & VIL-VCU)", url: "https://www.besacc-vca.be/fr/erkende-examencentra-b-vca-vol-vca-vil-vcu/",
      note: "Liste lue le 2026-10-01 : Wisy Safety n'y figure pas." },
    { id: "DOC-CSM-CDR", type: "Official", org: "Contractor Safety Management",
      title: "Centraal Diplomaregister (registre central des diplômes VCA)", url: "https://csm-examen.be/cdr" },
    { id: "DOC-SSVV-2026", type: "Professional", org: "SSVV — Stichting Samenwerken Voor Veiligheid (propriétaire du schéma VCA, Pays-Bas)",
      title: "Wat verandert er aan de VCA-examens in 2026 ? (mis à jour le 29-4-2026)", url: "https://ssvv.nl/actueel/wat-verandert-er-aan-de-vca-examens-in-2026-2/" },
    { id: "DOC-BESACC-BASE", type: "Official", org: "BeSaCC-VCA", title: "Sécurité de base (B-VCA)", url: "https://www.besacc-vca.be/fr/basisveiligheid-b-vca/" },
    { id: "DOC-CONSTRUCTIV-PRIMES", type: "Official", org: "Constructiv — fonds sectoriel de la construction", title: "Primes de formation", url: "https://constructiv.be/fr/soutiens-aux-travailleurs/primes-de-formation/" },
    { id: "DOC-FOA-FIBER", type: "Professional", org: "The Fiber Optic Association (FOA)", title: "FOA Reference Guide — Optical Fiber", url: "https://www.thefoa.org/tech/ref/basic/fiber.html" },
    { id: "DOC-FOA-LOSS", type: "Professional", org: "The Fiber Optic Association (FOA)", title: "Guidelines On What Loss To Expect When Testing Fiber Optic Cables", url: "https://www.thefoa.org/tech/loss-est.htm" },
    { id: "DOC-FOA-TEST", type: "Professional", org: "The Fiber Optic Association (FOA)", title: "FOA Reference Guide — Fiber Optic Testing", url: "https://www.thefoa.org/tech/ref/basic/test.html" },
    { id: "DOC-FOA-CFOT", type: "Professional", org: "The Fiber Optic Association (FOA)", title: "The Fiber Optic Association CFOT Certification", url: "https://www.thefoa.org/cfot.htm" },
    { id: "DOC-ITU-G652", type: "Professional", org: "Union internationale des télécommunications (UIT)", title: "Recommendation ITU-T G.652 (08/2024) — Characteristics of a single-mode optical fibre and cable",
      url: "https://www.itu.int/epublications/publication/itu-t-g-652-2024-08-characteristics-of-a-single-mode-optical-fibre-and-cable",
      note: "Résumé lu : https://www.itu.int/dms_pubrec/itu-t/rec/g/T-REC-G.652-201611-S!!SUM-HTM-E.htm (édition 11/2016). Contenu payant de la norme non reproduit." },
    { id: "DOC-ITU-G652-SUM", type: "Professional", org: "Union internationale des télécommunications (UIT)", title: "Summary — ITU-T Rec. G.652 (11/2016)", url: "https://www.itu.int/dms_pubrec/itu-t/rec/g/T-REC-G.652-201611-S!!SUM-HTM-E.htm" },
    { id: "DOC-ITU-G657", type: "Professional", org: "Union internationale des télécommunications (UIT)", title: "Recommendation ITU-T G.657 (08/2024) — Characteristics of a bending-loss insensitive single-mode optical fibre and cable",
      url: "https://www.itu.int/epublications/publication/itu-t-g-657-2024-08-characteristics-of-a-bending-loss-insensitive-single-mode-optical-fibre-and-cable" },
    { id: "DOC-CISCO-CCNA", type: "Professional", org: "Cisco Systems", title: "CCNA — exams and training", url: "https://www.cisco.com/site/us/en/learn/training-certifications/certifications/enterprise/ccna/index.html" },
    { id: "DOC-KBO-WISY", type: "Official", org: "SPF Économie — Banque-Carrefour des Entreprises (BCE, KBO Public Search)",
      title: "Entité enregistrée 1027.725.391 — WISY", url: "https://kbopub.economie.fgov.be/kbopub-m/enterprise/1027725391",
      note: "Situation au 30 septembre 2026 : ACTIF ; forme légale ASBL depuis le 14 septembre 2025 ; dénomination « WISY » ; siège Avenue d'Itterbeek 378 bte 1, 1070 Anderlecht." },
    { id: "DOC-WISY-LEGACY", type: "Primary (Wisy Safety)", org: "Wisy Safety — ancien site (wisysafety.be)",
      title: "Pages fibre-optique, produit-dangereux, vca-ligne-hierarchique et bordereau /sinscrire/ (archives : content/_legacy/)", url: "https://wisysafety.be/",
      note: "Données internes PUBLIÉES par Wisy Safety, mais contradictoires entre elles (prix, durées) : seul le contenu pédagogique (niveaux, modules, formats, publics, conseils) est repris ; tout chiffre interne reste « à confirmer par écrit »." }
  ];

  /* ------------------------------------------------------------------ affirmations publiées */
  var P_VLH = ["formation-vca-ligne-hierarchique.html"], P_DII = ["formation-diisocyanates.html"], P_FIB = ["formation-fibre-optique.html", "article-fibre-devenir-expert.html"];
  var CLAIMS = [
    /* ---- VCA Ligne hiérarchique ---- */
    { id: "SRC-VLH-001", pages: P_VLH, doc: "DOC-BESACC-VOL", status: "Verified",
      text: "Dans le système VCA, toute personne responsable de personnel opérationnel doit être titulaire du diplôme « Sécurité pour les cadres opérationnels » (VOL-VCA), délivré par un centre d'examen reconnu (checklist VCA, question 3.3).",
      passage: "« toutes les personnes responsables du personnel opérationnel doivent être titulaires d'un diplôme \"Sécurité pour les gestionnaires opérationnels\" du CCN, délivré par un centre d'examen reconnu, qui ne date pas de plus de dix ans (à compter de la date de l'examen). (question 3.3. du CCN) »",
      notes: "Exigence de la checklist VCA (entreprises certifiées VCA) — formulé « dans le système VCA », pas comme une obligation légale générale. Intitulé officiel FR : « gestionnaires » sur la page, « cadres opérationnels » dans le règlement des examens (SCO-VCA)." },
    { id: "SRC-VLH-002", pages: P_VLH, doc: "DOC-BESACC-VOL", status: "Corrected",
      text: "Le diplôme VOL-VCA est valable 10 ans à compter du jour de l'examen.",
      passage: "« qui ne date pas de plus de dix ans (à compter de la date de l'examen) »",
      second: { doc: "DOC-VI-REGLEMENT-2024", passage: "« Le diplôme a une durée de validité de 10 ans, à compter du jour de l'examen. »" },
      notes: "Ancien site : « Certification valable 10 ans » rattachée à une formule tarifaire — corrigé : c'est la validité du DIPLÔME délivré par le centre d'examen." },
    { id: "SRC-VLH-003", pages: P_VLH, doc: "DOC-BESACC-VOL", status: "Verified",
      text: "Pour les cadres, les connaissances attendues comprennent tous les éléments de la « Sécurité de base » et, en plus, celles qu'exige la mission d'encadrement.",
      passage: "« Pour les managers, ces connaissances comprennent tous les éléments de la \"Sécurité de base CSC\" et, en outre, les connaissances spécifiques requises pour remplir la tâche de manager dans le cadre de l'exécution sûre du travail. »" },
    { id: "SRC-VLH-004", pages: P_VLH, doc: "DOC-BESACC-CENTRES", status: "Corrected",
      text: "Le diplôme VOL-VCA est délivré par un centre d'examen reconnu par BeSaCC-VCA, après réussite de l'examen — pas par Wisy Safety.",
      passage: "Liste « Centres d'examen reconnus (B-VCA, VOL-VCA & VIL-VCU) » (51 centres listés le 2026-10-01 ; Wisy Safety absent).",
      second: { doc: "DOC-BESACC-VOL", passage: "« délivré par un centre d'examen reconnu »" },
      notes: "Ancien site : « obtenez la certification VCA reconnue », « Examen VCA inclus », « Formateurs certifiés » — retirés tant que Wisy Safety n'a pas confirmé avec quel centre reconnu l'examen est organisé." },
    { id: "SRC-VLH-005", pages: P_VLH, doc: "DOC-CONSTRUCTIV-VCA", status: "Corrected",
      text: "Examen sur ordinateur de 70 questions de plusieurs types : choix multiples, matrices, classements, appariements.",
      passage: "« VOL 45 points ou plus sur un total de 70 » ; types : « questions à choix multiples… matrice… par classement… par appariement… avec un aperçu de la situation dans l'image »",
      second: { doc: "DOC-VI-REGLEMENT-2024", passage: "« des questions à choix multiple, des réponses multiples, des questions sous forme de matrice, de questions de classement, de questions de correspondance… » ; score par question : 0 à 100 points ; VOL-VCA sur 7 000 points" },
      notes: "Ancien site : « QCM de 70 questions » — corrigé : plusieurs types de questions, pas seulement un QCM. SSVV (NL) annonce 60 questions pour les examens renouvelés en 2026 : voir SRC-VLH-010." },
    { id: "SRC-VLH-006", pages: P_VLH, doc: "DOC-CSM-REGLEMENT", status: "Corrected",
      text: "Seuil de réussite : 64,5 % — soit au moins 4 515 points sur 7 000.",
      passage: "Art. 32.1 « Le candidat a réussi s'il a obtenu un score de : 64,5% pour la Sécurité de base VCA (B-VCA), Sécurité pour les Cadres Opérationnels VCA (SCO-VCA)… »",
      second: { doc: "DOC-VI-REGLEMENT-2024", passage: "« 4515/7000 (64,5%) pour les examens VOL-VCA et VIL-VCU »" },
      notes: "Ancien site : « note minimale 45/70 » (64,3 %) — corrigé selon le règlement (Constructiv écrit aussi « 45 points sur 70 », arrondi : le règlement fait foi)." },
    { id: "SRC-VLH-007", pages: P_VLH, doc: "DOC-BESACC-ETT-VOL", status: "Verified",
      text: "Les termes finaux de l'examen VOL-VCA s'organisent en 14 chapitres (législation, dangers, accidents, comportement, tâches et concertation, procédures, urgences, substances dangereuses, incendie, équipements de travail, travaux spécifiques, électricité et rayonnements, ergonomie, EPI).",
      passage: "Sommaire p. 2 : « 01. Wetgeving … 14. Persoonlijke beschermingsmiddelen (PBM) »",
      notes: "Intitulés traduits du néerlandais par Wisy Safety (mention affichée). Ancien site : « législation, prévention, EPI, travaux en hauteur » — remplacé par la liste officielle complète." },
    { id: "SRC-VLH-008", pages: P_VLH, doc: "DOC-VI-REGLEMENT-2024", status: "Verified",
      text: "Durée : 75 minutes selon le règlement d'un centre d'examen reconnu (Veiligheidsinstituut, version du 06/11/2024) ; la durée est confirmée par le centre.",
      passage: "Tableau « Types d'examens » : « VOL-VCA choix multiple — Durée : 75 min »",
      notes: "Le règlement général BeSaCC ne fixe la durée que pour la sécurité de base (60 min) : la durée VOL est donnée avec son centre d'origine." },
    { id: "SRC-VLH-009", pages: P_VLH, doc: "DOC-CSM-CDR", status: "Verified",
      text: "Le diplôme est inscrit au registre central des diplômes VCA, consultable par numéro de diplôme ou par nom et date de naissance.",
      passage: "« Zoek op diplomanummer, of op een combinatie van familienaam en geboortedatum. »",
      second: { doc: "DOC-VI-REGLEMENT-2024", passage: "« Le RCD rassemble tous les diplômes VCA (B-VCA, VOL-VCA et VIL-VCU)… fonction de recherche (par numéro de diplôme ou par une combinaison de la date de naissance et du nom de famille) »" } },
    { id: "SRC-VLH-010", pages: P_VLH, doc: "DOC-SSVV-2026", status: "Verified",
      text: "Aux Pays-Bas, SSVV a renouvelé ses examens en 2026 (VOL-VCA : 60 questions, 60 minutes) ; les règlements belges consultés indiquent encore le format de 70 questions.",
      passage: "« De huidige VOL-VCA en VIL-VCU examens bestaan uit 70 vragen, maar de nieuwe uit 60 vragen. De standaard examentijd … is daarom bij de vernieuwde examens 60 minuten. » ; « 1 januari 2026 zijn we gestart … in het Nederlands. »",
      notes: "Application en Belgique non documentée par BeSaCC-VCA au 2026-10-01 : à surveiller (point de vigilance du rapport)." },
    { id: "SRC-VLH-011", pages: P_VLH, doc: "DOC-CONSTRUCTIV-PRIMES", status: "Corrected",
      text: "Construction : Constructiv prévoit des primes de formation pour les ouvriers et des interventions dans les frais de formation pour l'employeur, selon ses propres conditions.",
      passage: "« Constructiv prévoit différentes formations dont nous prenons les frais en charge. En outre, vous pouvez bénéficier de différentes primes de formation » ; « Votre employeur bénéficie en outre d'une intervention dans les frais de formation »",
      notes: "Ancien site : « peut être prise en charge … via Constructiv/CP124, Forem, Actiris, VDAB » — reformulé prudemment, sans garantie ; Actiris, Bruxelles Formation, Le Forem et VDAB cités comme organismes à contacter (liens vers leurs sites), sans affirmation de prise en charge." },
    { id: "SRC-VCAB-EXAM", pages: P_VLH, doc: "DOC-CSM-REGLEMENT", status: "Verified",
      text: "VCA Base (B-VCA) : 40 questions, 60 minutes, seuil de 64,5 %.",
      passage: "Art. 35.5 « Pour l'examen Sécurité de Base sur ordinateur le candidat dispose de 60 minutes » ; art. 32.1 « 64,5% pour la Sécurité de base VCA »",
      second: { doc: "DOC-CONSTRUCTIV-VCA", passage: "« Base 26 points ou plus sur un total de 40 » ; VI : « 2580/4000 (64,5%) pour l'examen de base VCA »" } },
    { id: "SRC-VCAB-VALID", pages: P_VLH, doc: "DOC-BESACC-BASE", status: "Verified",
      text: "Le diplôme VCA Base est valable 10 ans.",
      passage: "« diplôme de \"sécurité de base\" du VCA, délivré par un centre d'examen reconnu, datant de moins de dix ans (à compter de la date de l'examen). (question 3.2 du VCA) »" },

    /* ---- Diisocyanates ---- */
    { id: "SRC-DII-001", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Verified",
      text: "Le règlement (UE) 2020/1149 de la Commission du 3 août 2020 a ajouté les diisocyanates à l'annexe XVII du règlement REACH (entrée 74) ; publié au JO L 252 du 4.8.2020.",
      passage: "Titre ; en-tête « 4.8.2020 — Journal officiel de l'Union européenne — L 252/24 » ; annexe « l'entrée suivante est ajoutée : 74. Diisocyanates… »" },
    { id: "SRC-DII-002", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Corrected",
      text: "Depuis le 24 août 2023, les diisocyanates ne peuvent être utilisés à titre industriel ou professionnel que si leur concentration est inférieure à 0,1 % en poids, ou si l'utilisateur a suivi avec succès, avant l'utilisation, une formation sur leur utilisation sûre.",
      passage: "Entrée 74, point 1 : « Ne peuvent être utilisés … après le 24 août 2023, sauf si : a) la concentration … est inférieure à 0,1 % en poids, ou b) l'employeur ou le travailleur indépendant veille à ce que le(s) utilisateur(s) … ai(en)t suivi avec succès une formation sur l'utilisation sûre des diisocyanates avant l'utilisation »",
      notes: "Ancien site : « Le règlement REACH 2020/1149/UE est entré en vigueur le 24 août 2023 » — corrigé : le règlement est entré en vigueur le 20e jour suivant sa publication (art. 2) ; c'est l'OBLIGATION de formation qui s'applique depuis le 24 août 2023. « Formation certifiée » corrigé en « formation suivie avec succès »." },
    { id: "SRC-DII-003", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Verified",
      text: "Seuil : 0,1 % en poids de diisocyanates, individuellement et en combinaison ; la restriction vise les usages industriels et professionnels.",
      passage: "Entrée 74, point 1 a) « la concentration en diisocyanates, individuellement et en combinaison, est inférieure à 0,1 % en poids » ; « pour usage(s) industriel(s) et professionnel(s) »",
      notes: "Ancien site : « plus de 0,1 % » — corrigé : la restriction s'applique dès 0,1 % (exemption seulement en dessous)." },
    { id: "SRC-DII-004", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Verified",
      text: "Sont visés les travailleurs salariés et les indépendants qui manipulent ces produits, ou qui supervisent ces tâches.",
      passage: "Point 3 : « tout travailleur salarié ou travailleur indépendant qui manipule des diisocyanates … ou qui supervise ces tâches »" },
    { id: "SRC-DII-005", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Corrected",
      text: "La formation est renouvelée au moins tous les cinq ans.",
      passage: "Point 8 : « La formation est renouvelée au moins tous les cinq ans. »",
      notes: "Ancien site : « Validité 5 ans », « Certification 5 ans — validité longue durée » — corrigé : renouvellement AU MOINS tous les cinq ans." },
    { id: "SRC-DII-006", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Corrected",
      text: "L'employeur ou l'indépendant atteste de la réussite de la formation ; le règlement ne crée pas de « certificat européen ».",
      passage: "Point 8 : « L'employeur ou le travailleur indépendant atteste de la réussite de la formation visée aux points 4 et 5. »",
      notes: "Ancien site : « Certification valide partout en Europe », « Reconnaissance légale européenne » — retirés." },
    { id: "SRC-DII-007", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Verified",
      text: "Formation par un expert en sécurité et santé au travail ; trois niveaux (général, intermédiaire, avancé) selon les usages, contenus minimaux, « y compris en ligne », certification ou preuve documentée de réussite.",
      passage: "Point 4 (expert ; usages par niveau) et point 5 a) b) c) (éléments de formation ; « y compris en ligne » ; « certification ou preuves documentées montrant qu'une formation a été suivie avec succès »)",
      notes: "Ancien site : liste de contenus (« procédures d'urgence et premiers secours », « obligation de signalement ») non conforme au texte — remplacée par les éléments du point 5." },
    { id: "SRC-DII-008", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Verified",
      text: "La formation respecte les dispositions fixées par l'État membre dans lequel l'utilisateur travaille.",
      passage: "Point 6 : « La formation est conforme aux dispositions fixées par l'État membre dans lequel opère(nt) le(s) utilisateur(s) industriel(s) ou professionnel(s). »" },
    { id: "SRC-DII-009", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Verified",
      text: "Depuis le 24 février 2022, le fournisseur transmet les informations sur l'exigence de formation et fait figurer sur l'emballage la mention « À partir du 24 août 2023, une formation adéquate est requise avant toute utilisation industrielle ou professionnelle ».",
      passage: "Point 2 b), citation exacte de la mention." },
    { id: "SRC-DII-010", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Verified",
      text: "Les diisocyanates sont classés sensibilisants respiratoires de catégorie 1 et sensibilisants cutanés de catégorie 1 (classification harmonisée, règlement CLP).",
      passage: "Considérant 1 : « classés, selon la classification harmonisée, comme sensibilisant respiratoire de catégorie 1 et comme sensibilisant cutané de catégorie 1 conformément au règlement (CE) no 1272/2008 »" },
    { id: "SRC-DII-011", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Verified",
      text: "Le dossier à l'origine de la restriction estimait à plus de 5 000 par an les nouveaux cas de maladies professionnelles imputables aux diisocyanates ; la sensibilisation respiratoire provoque un asthme professionnel.",
      passage: "Considérant 2 : « provoque un asthme professionnel chez les travailleurs… Le nombre annuel de nouveaux cas de maladies professionnelles imputables aux diisocyanates (estimé à plus de 5 000 cas) »",
      notes: "Chiffre cité comme ESTIMATION du dossier de restriction, avec sa source ; non arrondi, non actualisé." },
    { id: "SRC-DII-012", pages: P_DII, doc: "DOC-SPF-VLE-2026", status: "Verified",
      text: "En Belgique, l'arrêté royal du 25 mai 2026 (Moniteur belge du 3 juin 2026) fixe pour l'ensemble des diisocyanates 10 µg NCO/m³ sur 8 heures et 20 µg NCO/m³ en courte durée, abaissés à 6 et 12 µg NCO/m³ à partir du 1er janvier 2029.",
      passage: "« une valeur limite pour une période de référence de 8 heures de 10 µg NCO/m³, combinée à une valeur limite d'exposition de courte durée de 20 µg NCO/m³. À partir du 1er janvier 2029, celles-ci sont abaissées à 6 µg NCO/m³ … et à 12 µg NCO/m³ »",
      notes: "Deuxième source souhaitable : texte de l'AR au Moniteur belge (lien donné par la page du SPF) — non relu." },
    { id: "SRC-DII-013", pages: P_DII, doc: "DOC-SPF-AGENTS-CHIM", status: "Verified",
      text: "L'employeur doit évaluer les risques liés aux agents chimiques présents sur le lieu de travail et prendre les mesures de prévention qui s'imposent (Code du bien-être au travail, livre VI, titre 1er).",
      passage: "« Cette matière est régie par le titre 1er relatif aux agents chimiques, du livre VI du code du bien-être au travail. … Les employeurs sont tenus d'évaluer les risques … et de prendre les mesures de prévention qui s'imposent. »",
      notes: "Remplace la liste non sourcée de l'ancien site (« Fournir EPI », « Assurer la ventilation »…)." },
    { id: "SRC-DII-014", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Verified",
      text: "Les diisocyanates sont utilisés dans un large éventail de secteurs et d'applications, notamment dans les mousses, les agents d'étanchéité et les revêtements.",
      passage: "Considérant 1 : « utilisés comme éléments constitutifs chimiques dans un large éventail de secteurs et d'applications, notamment, entre autres, dans les mousses, les agents d'étanchéité et les revêtements »" },
    { id: "SRC-DII-015", pages: P_DII, doc: "DOC-ISOPA", status: "Verified",
      text: "Les diisocyanates aromatiques (MDI, TDI) sont, avec les polyols, les principales matières premières des polyuréthanes (mousses rigides d'isolation, mousses souples des matelas).",
      passage: "« ISOPA represents the manufacturers of aromatic diisocyanates and polyols, the main raw materials for polyurethanes in Europe. » ; « It is by reacting diisocyanates (MDI and/or TDI) with polyols that you obtain polyurethanes … From the rigid foam that is used to insulate your house to the flexible foam used for mattresses »" },
    { id: "SRC-DII-016", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Verified",
      text: "Définition REACH : composés de formule O=C=N–R–N=C=O, R étant une unité d'hydrocarbure aliphatique ou aromatique de longueur non spécifiée.",
      passage: "Intitulé de l'entrée 74 : « Diisocyanates, O = C=N-R-N = C=O, R étant une unité d'hydrocarbure aliphatique ou aromatique de longueur non spécifiée »" },
    { id: "SRC-DII-017", pages: P_DII, doc: "DOC-ECHA-DIISO", status: "Corrected",
      text: "L'ECHA regroupe 14 substances sous « Diisocyanates », dont MDI, TDI (isomères 2,4 et 2,6), HDI, IPDI et NDI.",
      passage: "« Group members » : Hexamethylene diisocyanate ; 4,4'-methylenediphenyl diisocyanate ; 4-methyl-m-phenylene diisocyanate ; 2-methyl-m-phenylene diisocyanate ; 3-isocyanatomethyl-3,5,5-trimethylcyclohexyl isocyanate ; 1,5-naphthylene diisocyanate…",
      notes: "Ancien site : « MDI = 70 % de la consommation mondiale » (aucune source) — retiré ; usages par substance (NDI « revêtements haute performance »…) non sourcés — retirés." },
    { id: "SRC-DII-018", pages: P_DII, doc: "DOC-ALIPA", status: "Verified",
      text: "Le HDI et l'IPDI sont des diisocyanates aliphatiques, transformés notamment en durcisseurs pour des revêtements et des adhésifs de haute qualité, à usage industriel et professionnel.",
      passage: "« Aliphatic polyisocyanates are manufactured by converting monomeric diisocyanates, e.g. HDI (hexamethylene diisocyanate) or IPDI (isophorone diisocyanate)… mainly used as hardeners for high quality surface coatings and adhesives in industrial and professional applications »" },
    { id: "SRC-DII-019", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Verified",
      text: "Les experts de l'ECHA ont estimé que la restriction réduirait aussi les cas de dermatite liés aux diisocyanates.",
      passage: "Considérant 4 : « il a estimé que la mise en œuvre de la restriction proposée modifiée réduirait également le nombre de cas de dermatite liés aux diisocyanates »" },
    { id: "SRC-DII-020", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Verified",
      text: "Aucun seuil n'est connu pour l'effet sensibilisant des diisocyanates.",
      passage: "Considérant 6 : « aucun seuil n'est connu pour l'effet sensibilisant des diisocyanates »" },
    { id: "SRC-DII-021", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Verified",
      text: "Le fournisseur veille à ce que le destinataire reçoive le matériel et les cours de formation dans la ou les langues officielles de l'État membre concerné.",
      passage: "Point 7." },
    { id: "SRC-DII-022", pages: P_DII, doc: "DOC-EURLEX-1999-77", status: "Corrected",
      text: "Amiante : asbestoses, mésothéliomes et cancers du poumon ; aucun seuil sans risque de cancer déterminé pour le chrysotile ; États membres en conformité au plus tard le 1er janvier 2005.",
      passage: "Considérant 1 (« provoquer des asbestoses, des mésothéliomes et des cancers du poumon ») ; considérant 7 (« il n'a pas encore pu être déterminé de seuil d'exposition au-dessous duquel l'amiante chrysotile n'entraine pas de risque de cancer ») ; considérant 9 (« interdire l'utilisation des fibres d'amiante chrysotile ») ; article 2 (« au plus tard le 1er janvier 2005 »)",
      notes: "Ancien site : « totalement interdite en Europe depuis 2005 » et niveau de danger « ⚠️⚠️⚠️⚠️⚠️ » — reformulé selon le texte, échelle d'émojis supprimée." },
    { id: "SRC-DII-023", pages: P_DII, doc: "DOC-EURLEX-2017-2398", status: "Corrected",
      text: "Silice cristalline alvéolaire : cancérogénicité « amplement démontrée », travaux exposants inscrits à l'annexe I de la directive 2004/37/CE, valeur limite 0,1 mg/m³ ; composés du chrome (VI) cancérigènes : 0,005 mg/m³ (valeurs transitoires jusqu'au 17 janvier 2025).",
      passage: "Considérant 18 ; article 1er point 4 (« 6. Travaux exposant à la poussière de silice cristalline alvéolaire issue de procédés de travail ») ; annexe (« Poussière de silice cristalline alvéolaire — 0,1 » ; « Composés du chrome (VI) … 0,005 … 0,010 mg/m3 jusqu'au 17 janvier 2025 »)",
      notes: "Ancien site : « silicose », « ulcération cutanée et perforation du septum nasal » — non présents dans les textes consultés : retirés." },
    { id: "SRC-DII-024", pages: P_DII, doc: "DOC-EURLEX-2019-983", status: "Verified",
      text: "Formaldéhyde : cancérigène de catégorie 1B, sensibilisant cutané ; 0,37 mg/m³ (0,3 ppm) sur 8 heures, 0,74 mg/m³ (0,6 ppm) en courte durée.",
      passage: "Considérant 23 ; annexe (« Formaldéhyde 200-001-8 50-00-0 0,37 0,3 — 0,74 0,6 — Sensibilisation cutanée »)",
      notes: "Ancien site : « Formation recommandée » pour le formaldéhyde (non sourcé) — retiré. Acrylonitrile : retiré (aucune source consultée)." },
    { id: "SRC-DII-025", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Removed",
      text: "Le règlement (UE) 2020/1149 ne fixe aucun montant d'amende.",
      passage: "Lecture intégrale du texte : aucune disposition de sanction ni de montant.",
      notes: "Ancien site : « amendes jusqu'à 250 € par jour et par salarié non formé en Belgique » — SUPPRIMÉ (aucune source officielle belge trouvée). Le site renvoie vers le SPF Emploi et le conseiller en prévention." },
    { id: "SRC-DII-026", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Verified",
      text: "Le règlement est entré en vigueur le vingtième jour suivant sa publication (article 2).",
      passage: "Article 2 : « Le présent règlement entre en vigueur le vingtième jour suivant celui de sa publication au Journal officiel de l'Union européenne. »" },
    { id: "SRC-DII-027", pages: P_DII, doc: "DOC-EURLEX-2020-1149", status: "Verified",
      text: "La restriction s'applique sans préjudice des autres règles de sécurité et de santé au travail.",
      passage: "Point 10 : « La présente restriction s'applique sans préjudice d'autres actes législatifs de l'Union relatifs à la protection de la sécurité et de la santé des travailleurs sur le lieu de travail. »" },
    { id: "SRC-DII-028", pages: P_DII, doc: "DOC-ECHA-CRO3", status: "Corrected",
      text: "Le trioxyde de chrome figure sur la liste des substances soumises à autorisation de REACH (annexe XIV, entrée 16), date d'expiration au 21 septembre 2017.",
      passage: "« Chromium trioxide EC No.: 215-607-8 CAS No.: 1333-82-0 Entry No. 16 … Sunset Date 21-Sep-2017 »",
      notes: "Ancien site : « Restriction stricte en Europe (REACH Annex XIV) » — corrigé : l'annexe XIV est la liste d'AUTORISATION, pas une restriction." },

    /* ---- Fibre optique ---- */
    { id: "SRC-FIB-001", pages: P_FIB, doc: "DOC-FOA-FIBER", status: "Corrected",
      text: "Monomode : cœur d'environ 9 µm, lasers à 1310 et 1550 nm (téléphonie, télédistribution). Multimode : cœur de 50 ou 62,5 µm, utilisée à 850 et 1300 nm (réseaux locaux).",
      passage: "« Singlemode fiber has a much smaller core, only about 9 microns… It is used for telephony and CATV with laser sources at 1310 and 1550 nm » ; « Multimode … larger core (almost always 50 or 62.5 microns) … wavelengths of 850 and 1300 nm … for … local area networks »",
      notes: "Ancien site : « Atténuation 0,2–3,5 dB/km » sans source — remplacé par les valeurs typiques de la FOA (SRC-FIB-004)." },
    { id: "SRC-FIB-002", pages: P_FIB, doc: "DOC-ITU-G652-SUM", status: "Verified",
      text: "UIT-T G.652 : fibre monomode à dispersion nulle vers 1310 nm, utilisable aussi vers 1550 nm.",
      passage: "« single‑mode optical fibre and cable which has zero-dispersion wavelength around 1310 nm. The ITU‑T G.652 fibre was originally optimized for use in the 1310 nm wavelength region, but can also be used in the 1550 nm region. »",
      second: { doc: "DOC-ITU-G652", passage: "Page de la recommandation G.652 (08/2024) — titre et édition en vigueur." } },
    { id: "SRC-FIB-003", pages: P_FIB, doc: "DOC-ITU-G657", status: "Verified",
      text: "UIT-T G.657 : fibre monomode moins sensible aux courbures, notamment pour les réseaux d'accès et l'intérieur des bâtiments.",
      passage: "« designed for improved bending loss performance compared to ITU-T G.652 fibers, particularly for use in access networks and inside buildings »" },
    { id: "SRC-FIB-004", pages: P_FIB, doc: "DOC-FOA-LOSS", status: "Corrected",
      text: "Pertes typiques pour un budget optique : environ 0,3 dB par connecteur, 0,15 dB par épissure par fusion en monomode ; connecteurs pré-polis à épissure mécanique : 0,75 dB au maximum (TIA-568) ; la perte d'insertion est exigée par les normes pour qualifier une liaison ; OTDR pour les longues liaisons avec épissures ou le dépannage.",
      passage: "« we usually figure 0.3 dB loss for most adhesive/polish or fusion splice-on connectors. The loss spec for prepolished/mechanical splice connectors … will be higher (0.75 max per EIA/TIA 568) » ; « 0.15dB for singlemode fusion splices » ; « All standards require an insertion loss test for qualification of the link loss » ; « OTDRs are used for verifying individual events like splice loss on long links with inline splices or for troubleshooting »",
      notes: "Ancien site : « perte < 0,1 dB », « < 0,05 dB », « connecteurs mécaniques 0,3–0,5 dB » — corrigés selon la FOA." },
    { id: "SRC-FIB-005", pages: P_FIB, doc: "DOC-FOA-TEST", status: "Verified",
      text: "Microscope d'inspection (100 à 200 fois), matériel de nettoyage, localisateur visuel de défauts (VFL, laser rouge visible).",
      passage: "« Optical inspection microscope, 100-200X video scope recommended » ; « Cleaning materials - dry cleaning kits or lint free cleaning wipes and pure alcohol » ; « visual fault locator (VFL) uses a visible laser … show breaks in fibers »" },
    { id: "SRC-FIB-006", pages: ["formation-fibre-optique.html", "article-fibre-parcours-professionnels.html", "article-fibre-devenir-expert.html"], doc: "DOC-FOA-CFOT", status: "Corrected",
      text: "CFOT : principale certification de la FOA pour les techniciens fibre ; examen écrit de 100 questions, au moins 70 bonnes réponses ; accès par une école agréée par la FOA ou par au moins deux ans d'expérience de terrain (certification directe).",
      passage: "« CFOT® … is the primary FOA certification for all fiber optic technicians » ; « The CFOT exam is a written exam consisting of 100 multiple choice, matching and true false questions. You must answer at least 70 questions correctly to pass. » ; « two paths … training at an FOA-Approved school or … experience … » ; « at least two years of relevant field experience »",
      notes: "Ancien site : « Certification internationalement reconnue », « Durée 3 à 5 jours » — non retrouvés sur la page de la FOA : retirés." },
    { id: "SRC-FIB-007", pages: ["formation-fibre-optique.html", "article-fibre-parcours-professionnels.html", "article-fibre-devenir-expert.html"], doc: "DOC-CISCO-CCNA", status: "Corrected",
      text: "CCNA : obtenue en réussissant l'examen 200-301 CCNA (fondamentaux des réseaux, accès réseau, connectivité et services IP, fondamentaux de la sécurité, automatisation et programmabilité).",
      passage: "« you must pass the exam … (200-301 CCNA) … This exam tests your knowledge and skills related to network fundamentals, network access, IP connectivity, IP services, security fundamentals, and automation and programmability. »",
      notes: "Ancien site : « Indispensable pour progresser vers ingénieur réseau » — reformulé en conseil (« utile pour évoluer »)." },
    { id: "SRC-FIB-008", pages: P_FIB, doc: "DOC-FOA-FIBER", status: "Verified",
      text: "Les fibres multimodes OM3 et OM4 (50/125 µm) sont optimisées pour les sources laser VCSEL à 850 nm.",
      passage: "Tableau : « 50/125 microns (OM3, G.651.1) … Optimized for 850 nm VCSELs » ; « 50/125 microns (OM4, G.651.1) … Optimized for 850 nm VCSELs, higher speed »" }
  ];

  /* Sources citées par chaque article (propriété JSON-LD `citation`) — clé = id de la page dans js/site-content.js. */
  var ARTICLE_SOURCES = {
    "article-vlh-communication": ["DOC-BESACC-ETT-VOL"], "article-vlh-erreurs": ["DOC-BESACC-ETT-VOL"], "article-vlh-culture": ["DOC-BESACC-ETT-VOL"],
    "article-dii-definition": ["DOC-EURLEX-2020-1149", "DOC-ECHA-DIISO", "DOC-ISOPA", "DOC-ALIPA"],
    "article-dii-reglementation": ["DOC-EURLEX-2020-1149", "DOC-SPF-VLE-2026", "DOC-SPF-AGENTS-CHIM"],
    "article-dii-substances": ["DOC-EURLEX-1999-77", "DOC-EURLEX-2017-2398", "DOC-EURLEX-2019-983", "DOC-ECHA-CRO3", "DOC-EURLEX-2020-1149", "DOC-SPF-VLE-2026"],
    "article-fibre-parcours": ["DOC-FOA-CFOT", "DOC-CISCO-CCNA"],
    "article-fibre-expert": ["DOC-FOA-FIBER", "DOC-ITU-G652-SUM", "DOC-ITU-G657", "DOC-FOA-LOSS", "DOC-FOA-TEST", "DOC-FOA-CFOT", "DOC-CISCO-CCNA"]
  };

  /* Liens externes publiés sans affirmation factuelle (orientation) : contrôlés aussi par scripts/check-external-links.js. */
  var ORIENTATION_LINKS = [
    { url: "https://www.actiris.brussels/fr/citoyens/apprendre-un-metier/", org: "Actiris" },
    { url: "https://www.bruxellesformation.brussels/trouver-une-formation/", org: "Bruxelles Formation" },
    { url: "https://www.leforem.be/", org: "Le Forem" },
    { url: "https://www.vdab.be/", org: "VDAB" }
  ];

  var byId = {};
  DOCUMENTS.forEach(function (d) { byId[d.id] = d; });
  function doc(id) { return byId[id] || null; }
  function claim(id) { return CLAIMS.filter(function (c) { return c.id === id; })[0] || null; }
  /* Statuts acceptés pour une affirmation AFFICHÉE (Removed : la source documente un retrait, le texte publié dit « aucun montant »). */
  var PUBLISHABLE = { Verified: 1, Corrected: 1, Removed: 1, "Primary (Wisy Safety) confirmed": 1 };

  return { CHECKED: CHECKED, DOCUMENTS: DOCUMENTS, CLAIMS: CLAIMS, ARTICLE_SOURCES: ARTICLE_SOURCES, ORIENTATION_LINKS: ORIENTATION_LINKS,
    PUBLISHABLE: PUBLISHABLE, doc: doc, claim: claim };
});
